name: "KeeneticToMqtt"
description: "keenetic api to mqtt bridge"
version: "0.0.1"
slug: "keenetic_to_mqtt"
image: "blenderist/keenetictomqtt-{arch}"
url: "https://github.com/BlenderistDev/keeneticToMqtt"
arch:
  - amd64
options:
  keenetic:
    host: ""
    login: ""
    password: ""
  mqtt:
    host: ""
    login: ""
    password: ""
    clientId: keeneticToMqtt
    baseTopic: keeneticToMqtt
  homeassistant:
    deviceId: keeneticToMqtt
    updateInterval: 10s
    whitelist: []
schema:
  keenetic:
    host: str
    login: str
    password: str
  mqtt:
    host: str
    login: str
    password: str
    clientId: str
    baseTopic: str
  homeassistant:
    deviceId: str
    updateInterval: str
    whitelist:
      - str
